---
title: "Data Structures"
output: html_document
---

#vectors

```{r}
(grand_slam_win <- c(9, 15, 5, 12, 18))
```




```{r}
(grand_slam_win <- c(9, c(15, 5), c(12, 18)))
```




```{r}
a= c(1,2,3)
a2=c(1L,2L,3L)
b=c(4,2,1)
(d=c(a,b,a))
(d2=c("a","b","a"))

```


```{r}
typeof(a)
typeof(a2)
typeof(d2)

```


```{r}
c("A",2)
(g=c(F,2,3L,"ws"))
typeof(g)
```

```{r}
(a= c(1,20,3,40,5,60))
a[2]
a[c(2,1,4)]
a[-3]
a[-c(1,2)]
a[c(1,2,4,5)][-2]

```



```{r}
(a= c(1,20,3,40,5,60))
a[c(F,F,F,T,T,F)]
a[a>10]

```


```{r}
(grand_slam_win <- c("Andy Murray" = 9, "Rafael Nadal" = 15, 
                   "Stan Wawrinka" = 5, "Novak Djokovic" = 12, 
                   "Roger Federer" = 18))

grand_slam_win["Novak Djokovic"]
grand_slam_win[4]



```



```{r}
(grand_slam_win <- c("Andy Murray" = 9, "Rafael Nadal" = 15, 
                   "Stan Wawrinka" = 5, "Novak Djokovic" = 12, 
                   "Roger Federer" = 18))

length(grand_slam_win)
sum(grand_slam_win)
mean(grand_slam_win)
order(grand_slam_win)
sort(grand_slam_win)
grand_slam_win[order(grand_slam_win)]
sort(grand_slam_win,decreasing=TRUE)

```



```{r}
1:6
6:1
-6:1

```

```{r}
(today <- Sys.Date())
(three_months_ago <- seq(today, length = 2, by = "-3 months")[2])
library(quantmod)
getSymbols("AAPL", from = three_months_ago, to = today)
Xt = as.numeric(na.omit(ClCl(AAPL)))
mu <- mean(Xt)
(k <- mean((Xt - mu)^4)/(mean((Xt - mu)^2))^2 - 3)
```


```{r}
(mat <- matrix(1:12, ncol = 4,  nrow = 3))
mat[2,2]

```

```{r}
grand_slam_win <- c(9, 15, 5, 12, 18)
win_percentage <- c(78.07, 82.48, 63.96, 82.77, 81.80)

players <- c("Andy Murray", "Rafael Nadal", "Stan Wawrinka", 
             "Novak Djokovic", "Roger Federer")


mat=cbind(grand_slam_win,win_percentage)
dimnames(mat)[[1]]=players
dimnames(mat)[[2]]=c("number of grand slam","win percentage")
mat[c("Andy Murray","Rafael Nadal"),"number of grand slam"]


```


```{r}
mat[1:3,]

```

```{r}

(A <- matrix(1:8, 4, 2))
t(A)
dim(A)[1]
nrow(A)
length(A)
```

```{r}

(B <- matrix(1:4, 2, 2))
B*B
B%*%B

B_inv=solve(B)
B_inv%*%B

```


```{r}

library(quantmod)
today <- Sys.Date()
five_years_ago <- seq(today, length = 2, by = "-5 year")[2]
getSymbols("AAPL", from = five_years_ago, to = today)
getSymbols("NFLX", from = five_years_ago, to = today)
# Compute returns
Ra <- na.omit(ClCl(AAPL))
Rn <- na.omit(ClCl(NFLX)) 

# Estimation of mu and Sigma
Sigma <- cov(cbind(Ra, Rn))
mu <- c(mean(Ra), mean(Rn))

omega_star <- (Sigma[2, 2] - Sigma[1, 2])/(Sigma[1, 1] + Sigma[2, 2] - 2*Sigma[1, 2])

# Compute investment expected value and variance
mu_investment <- omega_star*mu[1] + (1 - omega_star)*mu[2]
var_investment <- omega_star^2*Sigma[1,1] + (1 - omega_star)^2*Sigma[2,2] + 
  2*omega_star*(1 - omega_star)*Sigma[1,2]

investment_summary <- matrix(NA, 2, 3)
dimnames(investment_summary)[[1]] <- c("Expected value", "Variance")
dimnames(investment_summary)[[2]] <- c("Apple", "Netflix", "Investment")
investment_summary[1, ] <- c(mu, mu_investment)
investment_summary[2, ] <- c(diag(Sigma), var_investment)
knitr::kable(investment_summary)

```

```{r}
# List elements
num_vec <- c(188, 140)
char_vec <- c("Height", "Weight", "Length")
logic_vec <- rep(TRUE, 8)
my_mat <- matrix(0, nrow = 5, ncol = 5)
# List initialization 
(my_list <- list(numeric=num_vec,char=char_vec,logic=logic_vec, my_mat))
my_list$numeric
my_list[[1]]
my_list[1]#----tricky
```



```{r}
my_List2=list(list=my_list,a=2)
my_List2$list$numeric
```


```{r}
### Creation

players <- c("Andy Murray", "Rafael Nadal", "Stan Wawrinka", 
             "Novak Djokovic", "Roger Federer")

grand_slam_win <- c(9, 15, 5, 12, 18)

date_of_birth <- c("15 May 1987", "3 June 1986", "28 March 1985", 
                  "22 May 1987", "8 August 1981")

country <- c("Great Britain", "Spain", "Switzerland", 
            "Serbia", "Switzerland")
ATP_ranking <- c(1, 2, 3, 4, 5)

prize_money <- c(60449649, 85920132, 30577981, 109447408, 104445185)

tennis <- data.frame(date_of_birth, grand_slam_win, country, 
                    ATP_ranking, prize_money)

dimnames(tennis)[[1]] <- players
tennis
View(tennis)
tennis[c("country")]

```


```{r}
expected_value=c(0.0009275, 0.0018499,0.0010563)
variance=c(0.0002109,0.0007084,0.0001975)



plot(NA,xlab='my x label',ylab='my y label',xlim=range(expected_value),ylim=range(variance))
grid()
points(expected_value, variance,pch=16,cex=2,col=c("red","blue","green"))

```

#Control Structures
```{r}

a=3
b=4
a>b
a<b
!(a>b)
!(a==b)
!(a!=b) || a > 0
!(a!=b) &&  a > 0
```

```{r}

a=3
b=4
a1=!(a!=b)
a2=a>b*0.4
!(a1 || a2) && TRUE

```


```{r}

a=1:12
sum(a>4)
a[a>4]
a[a>4 & a<10]
a>4 && a<10

```

```{r}
a=2
if (a>0){
  a=-a
}
a




a=21
if (a %% 2==0){
  print(paste(a,"is an even number"))
}else{
  print(paste(a,"is an odd number"))
}


```



```{r}

for (i in 1:6){
  print(i)
}

a=2
for (i in 1:6){
  if(a > 6){
    a=2
  }
  a=a+1
  } 
a

```


```{r}
a=1:6
sum(a)
n=length(a)
mysum=0
for(i in 1:n){
  mysum=mysum+a[i]
}
mysum/n
```












































